server:
  port: 7070

spring:
  application:
    name: turbine
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true
turbine:
  app-config: nacosconsumer #turbine监控的服务名称，可以多个
  aggregator:
    clusterConfig: default
  #instanceUrlSuffix:
    #default: hystrix.stream
  clusterNameExpression: new String("default")

