#provider.yml

# service
---
apiVersion: v1
kind: Service
metadata:
  name: nacosprovider-svc
  labels:
    app: nacosprovider
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: client
  selector:
    app: nacosprovider

#PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacosprovider-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

#msgpush Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacosprovider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacosprovider
  template:
    metadata:
      labels:
        name: nacosprovider
        app: nacosprovider
    spec:
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: nacosprovider-pvc
      containers:
        - name: nacosprovider
          imagePullPolicy: IfNotPresent
          image: "nacosprovider:v1"
          resources:
            requests:
              memory: "600Mi"
              cpu: "0.5"
          env:
            - name: "zk.curator.connectString"
              value: "zk-cs:2181"
            - name: "TZ"
              value: "Asia/Shanghai"
          ports:
            - containerPort: 8080
              name: client
          volumeMounts:
            - name: datadir
              mountPath: /logs
      securityContext:
        runAsUser: 1000
        fsGroup: 1000


