spring:
  application:
    name: zipkin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false
