spring:
  application:
    name: nacosconsumer

  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:9111
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    discovery-client-enabled: false


  sleuth:
    sampler:
      probability: 1.0
      rate: 50
